name: run-code-coverage

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: preview-${{ github.ref }}

jobs:
  run-code-coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version:  '3.10'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install urllib3

      - name: run coverage
        run: |
          coverage run -m test
          coverage html --omit='.venv/*'

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./htmlcov/
          preview-branch: main
          action: auto
        