name: run-code-coverage

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-code-coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version:  '3.10'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install urllib3

      - name: run coverage
        run: |
          coverage run -m test
          coverage html --omit='.venv/*'
      
      - name: Create gh-pages branch if it doesn't exist
        run: |
          git fetch origin
          if ! git rev-parse --verify origin/gh-pages-${{ github.event.pull_request.number }}; then
            git checkout --orphan gh-pages-${{ github.event.pull_request.number }}
            git reset --hard
            git commit --allow-empty -m "Initial commit on gh-pages-${{ github.event.pull_request.number }}"
            git push origin gh-pages-${{ github.event.pull_request.number }}
          fi
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmlcov
          publish_branch: gh-pages-${{ github.event.pull_request.number }}
        