name: run-code-coverage

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  run-code-coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version:  '3.10'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install urllib3

      - name: run coverage
        run: |
          coverage run -m test
          coverage html --omit='.venv/*'

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with: 
          path: './htmlcov/'
      
      - name: deploy to Github Pages
        uses: actions/deploy-pages@v2
        id: deployment
        